### ISSUE TITLE
Youtube search not working

### ISSUE THREAD

**Issue by jordanmat** [bbonch/bbonch.github.io#1]
Chrome: 116.0.5845.188
Searcher: 8.1.6
Tested with all other extensions disabled.

Youtube search stopped working. Only this frame shows:
![image](https://github.com/bbonch/bbonch.github.io/assets/48982589/35d08223-869e-4e53-9328-f563a4e5a035)
Spotify and Deezer search still work ok.

Pleae let me know if you need more details.
Thanks.

**Comment by bbonch** [comment]
It is expected behavior. Check this repository https://github.com/bbonch/searcher-for-discogs.

**Comment by jordanmat** [comment]
So is it due to the Youtube quota?
